[package]
name = "trane-server"
version = "0.1.0"
edition = "2021"

[lib]
name = "trane_server"

[dependencies]
actix-web = "4"
parking_lot = { version = "0.12", features = ["hardware-lock-elision"] }
serde = {version = "1.0.190", features = ["derive"]}
serde_json = "1.0.108"
trane = "0.17.5"
